replicaCount: 1

image:
  repository: hello-gitops # This should be customized per application
  pullPolicy: IfNotPresent
  tag: "latest" # This will be updated by the CI/CD pipeline

service:
  type: ClusterIP
  port: 80
