apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: REPLACE_APP_NAME-REPLACE_ENV # This must match the base argocd-app.yaml placeholder
    patch: |-
      - op: replace
        path: /metadata/name
        value: hello-app-dev-dev
      - op: replace
        path: /spec/destination/namespace
        value: dev
      - op: replace
        path: /spec/source/helm/valueFiles
        value:
          - ../../../apps/hello-app-dev/values-dev.yaml
      - op: replace
        path: /spec/source/path
        value: apps/hello-app-dev
