apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: REPLACE_APP_NAME-REPLACE_ENV # Target the placeholder name in the base
  patch: |-
    - op: replace
      path: /metadata/name
      value: hello-gitops-prod
    - op: replace
      path: /spec/destination/namespace
      value: prod
    - op: replace
      path: /spec/source/helm/valueFiles
      value:
        - ../../../apps/hello-gitops/values-prod.yaml
