apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/argocd-app.yaml
patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: hello-gitops-dev # Target the placeholder name in the base
  patch: |-
    - op: replace
      path: /metadata/name
      value: hello-gitops-dev
    - op: replace
      path: /spec/destination/namespace
      value: dev
    - op: replace
      path: /spec/source/helm/valueFiles
      value:
        - ../../../apps/hello-gitops/values-dev.yaml
